#!/usr/bin/with-contenv /bin/sh

SERVICES_D=/etc/services.d/${PHP_PACKAGE}-fpm

function log() {
    echo "[${0##*/}] $1" >&2
}

#
#	ocnfigure services.d file for php-fpm
#
mkdir -p $SERVICES_D
echo "#!/usr/bin/execlineb -P" > ${SERVICES_D}/run

case "${PHP_PACKAGE}" in
	php7)
		PHP_EXECUTABLE="php-fpm7"
		;;
	php5)
		PHP_EXECUTABLE="php-fpm5"
		;;
esac

echo "${PHP_EXECUTABLE} -F" >> ${SERVICES_D}/run
chmod a+x ${SERVICES_D}/run

#
#	configure timezone
#
if [ ! -z ${TZ+set} ]; then
	log "Setting date.timezone: ${TZ}"
    sed -e "s|^;\?\s*date\.timezone.*|date.timezone = ${TZ}|" -i /etc/${PHP_PACKAGE}/php.ini
fi

