#!/bin/sh

source /etc/php-package

SERVICES_D=/etc/services.d/${PHP_PACKAGE}-fpm

mkdir -p $SERVICES_D
echo "#!/usr/bin/execlineb -P" > ${SERVICES_D}/run

case "${PHP_PACKAGE}" in
	php7)
		PHP_EXECUTABLE="php-fpm7"
		;;
	php5)
		PHP_EXECUTABLE="php-fpm5"
		;;
esac

echo "${PHP_EXECUTABLE} -F" >> ${SERVICES_D}/run
chmod a+x ${SERVICES_D}/run
