#!/usr/bin/env bash

. hooks/config.alpine.inc

## construct and execute the build command
#
if [ "$DOCKER_TAG" = "latest" ]; then
	ALPINE_VERSION="${latest_alpine}"
else
	ALPINE_VERSION="${DOCKER_TAG}"
fi

build_cmd=(docker build --build-arg ALPINE_VERSION="${ALPINE_VERSION}" -t ${IMAGE_NAME} .)

printf '\n---\n%s\n---\n\n' "${build_cmd[*]}"
"${build_cmd[@]}"