#!/usr/bin/env bash

## configure before including common code
#
# this is the latest release of PyPy
latest='3.6'

. hooks/post_push.inc

case "${image_tag}" in
	2.7|3.6)
		ALPINE_VERSION=3.11
		;;
esac

tags+=("${image_tag}-alpine${ALPINE_VERSION}")

push_tags