#! /usr/bin/env bash

. hooks/env

echo '--- post_push ---'

get_manifest_tool
manifest_cmd=(./manifest-tool push from-args "${manifest_args}" --platforms "${platforms}" --template "${DOCKER_REPO}:${TARGET_TAG}"-ARCHVARIANT --target "${DOCKER_REPO}:${TARGET_TAG}")
pretty_manifest_cmd="$(echo "${manifest_cmd[*]}" | sed -r -e "s/(--)/\\\ \n\t\1/g")"

printf '\n--- manifest command ---\n%s\n' "${pretty_manifest_cmd}"
"${manifest_cmd[@]}" || { echo "*** Could not push manifest."; exit 0; }
