#! /usr/bin/env bash

. hooks/env

for arch in ${valid_arches}; do
	TARGET_TAG="${arch}_TARGET_TAG"
	image="${DOCKER_REPO}:${DEB_RELEASE}-${!TARGET_TAG}"
	printf '*** Pushing: %s\n' "${image}"
	docker push "${image}" | grep digest
done
