#! /usr/bin/env bash

. hooks/env

echo '--- push ---'

for arch in ${valid_arches}; do
	TARGET_ARCH_TAG="${arch}_TARGET_ARCH_TAG"
	image="${DOCKER_REPO}:${TARGET_TAG}-${!TARGET_ARCH_TAG}"
	printf 'Pushing: %s\n' "${image}"
	docker push "${image}" | grep digest
	echo
done
