#!/usr/bin/env bash

case "${DOCKER_TAG}" in
	2.7-jessie)
		MINIDEB_RELEASE=jessie
		PYTHON_VERSION=2.7.9-1
		;;
	2.7-stretch)
		MINIDEB_RELEASE=stretch
		PYTHON_VERSION=2.7.13-2
		;;
	2.7-buster)
		MINIDEB_RELEASE=buster
		PYTHON_VERSION=2.7.16-1
		;;
	3.4-jessie)
		MINIDEB_RELEASE=jessie
		PYTHON_VERSION=3.4.2-2
		;;
	3.5-stretch)
		MINIDEB_RELEASE=stretch
		PYTHON_VERSION=3.5.3-1
		;;
	3.7-buster|*)
		MINIDEB_RELEASE=buster
		PYTHON_VERSION=3.7.3-1
		;;
esac

## construct and execute the build command
#
build_cmd=(docker build --build-arg MINIDEB_RELEASE="${MINIDEB_RELEASE}" --build-arg PYTHON_VERSION="${PYTHON_VERSION}" -t ${IMAGE_NAME} .)

printf '\n---\n%s\n---\n\n' "${build_cmd[*]}"
"${build_cmd[@]}"