#!/usr/bin/env bash

## configure before including common code
#
# this is the latest release of Alpine
latest='3.7-buster'

. hooks/post_push.inc

# this is the latest release with Python 3
if [ "${image_tag}" = "3.7-buster" ]; then
	tags+=('3')
fi

# this is the latest release with Python 2.7
if [ "${image_tag}" = "2.7-buster" ]; then
	tags+=('2' '2.7')
fi

# tag with python versions and OS release names
case "${image_tag}" in
	2.*)
		tags+=("2-${image_tag#*-}")
		;;
	3.*)
		tags+=("${image_tag%-*}" "${image_tag#*-}" "3-${image_tag#*-}")
		;;
esac

push_tags
