#!/usr/bin/with-contenv /bin/sh
# shellcheck shell=sh

# set PUID and PGID for www-data user/group
#
PUID=${PUID:-1000}
PGID=${PGID:-1000}

echo "[${0##*/}] uid: ${PUID}, gid: ${PGID}"

groupmod -o -g "$PGID" www-data
usermod -o -u "$PUID" -g "$PGID" www-data >/dev/null 2>&1

chown -R ${PUID}:${PGID} $WEB_ROOT

# server configuration
#
NGINX_PORT=${NGINX_PORT:-$DEFAULT_NGINX_PORT}
NGINX_INDEX=${NGINX_INDEX:-index.html index.htm}
WEB_ROOT=${WEB_ROOT:-$DEFAULT_WEB_ROOT}

sed -r \
	-e "s|^(\s+listen\D+)(\d+)(\D.*)$|\1${NGINX_PORT}\3|g" \
	-e "s|^\s+index.*$|\tindex\t\t${NGINX_INDEX};|g" \
	-e "s|^\s+root.*$|\troot\t\t${WEB_ROOT};|g" \
	-i /etc/nginx/http.d/default.conf

# enable logging of 200 and 300 HTTP codes
#
if [ ! -z "${NGINX_LOG_ALL+set}" ]; then
	case $(echo $NGINX_LOG_ALL | tr '[A-Z]' '[a-z]') in
		true|on|yes)
			sed -i 's|/dev/stdout combined if=$loggable;|/dev/stdout main;|' /etc/nginx/nginx.conf
			;;
	esac
fi
