#!/usr/bin/env bash

## construct and execute the build command
#
build_cmd=(docker build --build-arg ALPINE_VERSION=${DOCKER_TAG} -t ${IMAGE_NAME} .)

printf '\n---\n%s\n---\n\n' "${build_cmd[*]}"
"${build_cmd[@]}"
