#!/usr/bin/env bash

## set the PHP package string
#
case "${DOCKER_TAG}" in
	5*)
		PHP_PACKAGE=php5
		ALPINE_VERSION=3.7.3
		;;
	7*)
		PHP_PACKAGE=php7
		ALPINE_VERSION=3.12.3
		;;
esac

## construct and execute the build command
#
build_cmd=(docker build --build-arg ALPINE_VERSION=${ALPINE_VERSION} --build-arg PHP_VERSION=${DOCKER_TAG} --build-arg PHP_PACKAGE=${PHP_PACKAGE} -t ${IMAGE_NAME} .)

printf '\n---\n%s\n---\n\n' "${build_cmd[*]}"
"${build_cmd[@]}"