#!/usr/bin/env bash

## construct and execute the build command
#
case "${DOCKER_TAG}" in
	latest)
		build_cmd=(docker build -t ${IMAGE_NAME} .)
		;;
	*)
		build_cmd=(docker build --build-arg ALPINE_VERSION="${DOCKER_TAG}" -t ${IMAGE_NAME} .)
		;;
esac

printf '\n---\n%s\n---\n\n' "${build_cmd[*]}"
"${build_cmd[@]}"