#!/usr/bin/env bash

## construct and execute the build command
#
if [ "$DOCKER_TAG" = "latest" ]; then
	build_cmd=(docker build -t ${IMAGE_NAME} .)
else
	build_cmd=(docker build --build-arg ALPINE_VERSION="${DOCKER_TAG}" -t ${IMAGE_NAME} .)
fi

printf '\n---\n%s\n---\n\n' "${build_cmd[*]}"
"${build_cmd[@]}"