#!/usr/bin/with-contenv /bin/sh

UWSGI_INI="/etc/uwsgi.ini"

if [ ! -z ${UWSGI_LOG+set} ]; then
	case $UWSGI_LOG in
		true|True|TRUE|on|On|On)
#			sed -e "s|^disable-logging.*|disable-logging = false|" -i $UWSGI_INI
			sed "s|^disable-logging.*|disable-logging = false|" -i $UWSGI_INI
			;;
	esac
fi

