ARG ALPINE_VERSION="3.12.3"
ARG FROM_IMAGE="moonbuggy2000/alpine-s6-nginx:${ALPINE_VERSION}"

ARG QEMU_ARCH="arm"

## build the image
#
FROM multiarch/qemu-user-static:x86_64-${QEMU_ARCH} AS qemu
FROM ${FROM_IMAGE}

ARG QEMU_ARCH
COPY --from=qemu /usr/bin/qemu-${QEMU_ARCH}-static /usr/bin

COPY ./etc /etc

ENTRYPOINT ["/init"]
