#!/usr/bin/env sh

case "${DOCKER_TAG}" in
	3.10.3|alpine3.10.3)
		ALPINE_VERSION=3.10.3
		NGINX_VERSION=1.16
		;;
	3.7.3|alpine3.7.3)
		ALPINE_VERSION=3.7.3
		NGINX_VERSION=1.12
		;;
esac

arg_string=''

if [ ! -z "${ALPINE_VERSION}" ]; then
	arg_string="${arg_string} --build-arg ALPINE_VERSION=${ALPINE_VERSION}"
fi

if [ ! -z "${NGINX_VERSION}" ]; then
    arg_string="${arg_string} --build-arg NGINX_VERSION=${NGINX_VERSION}"
fi

echo "docker build ${arg_string} -t ${IMAGE_NAME} ."

docker build ${arg_string} -t ${IMAGE_NAME} .
