#!/usr/bin/env bash

. hooks/config.alpine.inc

## set the Nginx version
#
getNginxVersion ${DOCKER_TAG}

## construct and execute the build command
#
build_cmd=(docker build --build-arg ALPINE_VERSION=${DOCKER_TAG} --build-arg NGINX_VERSION=${NGINX_VERSION} -t ${IMAGE_NAME} .)

printf '\n---\n%s\n---\n\n' "${build_cmd[*]}"
"${build_cmd[@]}"