#!/usr/bin/env bash

. hooks/config.alpine.inc

latest=$latest_alpine

. hooks/post_push.inc

tags+=("alpine${image_tag}")

setNginxTag ${image_tag}

# these are the last releases for a minor version
case "${image_tag}" in
	$latest_alpine_minor)
		tags+=("${image_tag%.*}" "alpine${image_tag%.*}")
		;;
esac

push_tags
